name: BuildAll.OnPush.ToMaster

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    # that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE,
        # so your job can access it
        - uses: actions/checkout@v3
        - name: Login to Yandex Cloud Container Registry
          id: login-cr
          uses: yc-actions/yc-cr-login@v1
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
               
        - name: Build and push to YCR pay.coworkhub
          env:
            CR_REGISTRY: crp4odt1er9cmqarghdbAAAAAAAAA
            CR_REPOSITORY: containers-registryAAAAAAAAAAAA
            IMAGE_TAG: ${{ github.sha }}
          working-directory: .
          run: |
            docker build -t cr.yandex/crp4odt1er9cmqarghdb/sankirtanAAAAAA:${{ github.sha }} -f ./Dockerfile .
            docker push     cr.yandex/crp4odt1er9cmqarghdb/sankirtanAAAAAA:${{ github.sha }}
            
        - name: Deploy Pay.Coworkhub
          id: deploy-pay.coworkhub
          uses: yc-actions/yc-sls-container-deploy@v2
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            container-name: pay-coworkhub
            folder-id: b1gslim9pjl5jan2tbodAAAAAA
            revision-service-account-id: ajevd85hi4q5rgcernn2AAAAAAA
            revision-cores: 1
            revision-memory: 256Mb
            revision-core-fraction: 5
            revision-concurrency: 8
            revision-image-url: cr.yandex/crp4odt1er9cmqarghdb/sankirtanaAAAAAA:${{ github.sha }}
            revision-execution-timeout: 60
            revision-provisioned: 1
            revision-env: YA_OBJECT_STORAGE_SECRET_KEY=${{ secrets.YA_OBJECT_STORAGE_SECRET_KEY }}
